

export const data = {
	products: [
		{
            id: "1",
            name: 'Pink Polo Shirt',
            image: '/images/mrNobody.png',
            price: 120,
            countInStock: 10,
            rating: 4.5,
            numReviews: 10,
            description: 'high quality shirt',
		},
		{
            id: "2",
            name: 'Marl Polo Shirt',
            image: '/images/mrNobody.png',
            price: 250,
            countInStock: 0,
            rating: 4.0,
            numReviews: 10,
            description: 'high quality shirt',
		},
		{
            id: "3",
            name: 'Slim Fit Polo Shirt',
            image: '/images/mrNobody.png',
            price: 25,
            countInStock: 15,
            rating: 4.5,
            numReviews: 14,
            description: 'high quality product',
		},
		{
            id: "4",
            name: 'Orange Polo Shirt',
            image: '/images/mrNobody.png',
            price: 65,
            countInStock: 5,
            rating: 4.5,
            numReviews: 10,
            description: 'high quality shirt',
		},
		{
            id: "1",
            name: 'Pink Polo Shirt',
            image: '/images/mrNobody.png',
            price: 120,
            countInStock: 10,
            rating: 4.5,
            numReviews: 10,
            description: 'high quality shirt',
		},
		{
            id: "2",
            name: 'Marl Polo Shirt',
            image: '/images/mrNobody.png',
            price: 250,
            countInStock: 0,
            rating: 4.0,
            numReviews: 10,
            description: 'high quality shirt',
		},
		{
            id: "3",
            name: 'Slim Fit Polo Shirt',
            image: '/images/mrNobody.png',
            price: 25,
            countInStock: 15,
            rating: 4.5,
            numReviews: 14,
            description: 'high quality product',
		},
		{
            id: "4",
            name: 'Orange Polo Shirt',
            image: '/images/mrNobody.png',
            price: 65,
            countInStock: 5,
            rating: 4.5,
            numReviews: 10,
            description: 'high quality shirt',
		},
		{
            id: "1",
            name: 'Pink Polo Shirt',
            image: '/images/mrNobody.png',
            price: 120,
            countInStock: 10,
            rating: 4.5,
            numReviews: 10,
            description: 'high quality shirt',
		},
		{
            id: "2",
            name: 'Marl Polo Shirt',
            image: '/images/mrNobody.png',
            price: 250,
            countInStock: 0,
            rating: 4.0,
            numReviews: 10,
            description: 'high quality shirt',
		},
		{
            id: "3",
            name: 'Slim Fit Polo Shirt',
            image: '/images/mrNobody.png',
            price: 25,
            countInStock: 15,
            rating: 4.5,
            numReviews: 14,
            description: 'high quality product',
		},
		{
            id: "4",
            name: 'Orange Polo Shirt',
            image: '/images/mrNobody.png',
            price: 65,
            countInStock: 5,
            rating: 4.5,
            numReviews: 10,
            description: 'high quality shirt',
		},
	],
};